version: 2
updates:
- package-ecosystem: "github-actions"
  target-branch: "main"
  directory: "/"
  schedule:
      interval: "weekly"
- package-ecosystem: ""
  target-branch: "main"
  directory: "/"
  schedule:
      interval: "weekly"
