language: node_js
node_js:
- 10
before_script:
- npm run lint
before_deploy:
- npm run pkg
deploy:
  provider: releases
  api_key:
    secure: cvGQZUVIRQ4DBTq87D3O5scGjqBk2f4+xaAT1+R63l0Kl0UZS/Vj4/t4PMI57/jyx0VrrdlbdAj+lAjCFoAtnGq29snDYRJ2EkbWmbekdqWB+9pGzLyQbRz8KZI4mVbYm/06f2fXtpsWlfOITWQ2DzXAt1Bewd4za+/E9KakkQJ6zte8QxOne/c8DddakAWx4fyHV8chFhubNNUle39fyBnocfMC0fUT5K/+fn3Stg4FCR86Z7LouPIY8RC9wEYF8s73Vzmhk/ntvw6GAXcOYL9LaMROl15+Y9qKrGDsleB2LfPUKBdaAiatNct0bLjvX9VhK9XUXMbezZLKVNhoEbtbpL+2/a3CO4B1ndsFrtkPBBpkhzOD1UloHTAuGzBUuRcI54es60aH1H8VNwjMMKpfHFD2vLpbiPO7cAFImzMbJFTS8Vjg1UjjRq71WUhuYDZYof4JTc7YfNCPmnWwUQgDWryAChQL2CbJ2bnV459cEE1BShwVLp4DdVpgnOg3Ce65EmAcAgfaoGFVKNF6yn0D8Ox9Iz1xzn6A2YtHY/+ngVXDBeeVnXAgGPsKOyfqEWlohqRMF8+t01FVpbHtroqmBVcBByJMcbXOZWF5MB707LRluIMfFjqeKoOhtdiju4U7DRoqTPxWAImENIu81QiPCEHnbekcJrdjNgJYOCs=
  file_glob: true
  file: build/Release/csv-select-*
  skip_cleanup: true
  on:
    tags: true
    repo: abetomo/csv-select
